### ISSUE TITLE
ptex fonts interfere with tgothic font package

### ISSUE THREAD

**Issue by norbusan** [texjporg/ptex-fonts#2]
Please see https://tex.stackexchange.com/questions/410965/bookhands-tgothic-package-not-rendering-on-overleaf

**Comment by aminophen** [comment]
The font name in ptex-fonts should never been changed; I replied on http://tug.org/pipermail/tex-live/2018-January/040973.html

**Comment by norbusan** [comment]
As posted, the tgoth gothic fonts were not installed already back in 2011 by Karl due to name conflict, see https://www.tug.org/pipermail/tex-live/2011-August/030031.html
The original sx poster used files that should not be used in TL.

Sorry for the noise, closing this issue.
